[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts =
    --alluredir=allure-results
    --clean-alluredir
    -v
    -ra
    --strict-markers
    --tb=short
    --disable-warnings

markers =
    smoke: дымовые тесты
    regression: регрессионные тесты
    ui: UI-тесты
    negative: негативные сценарии
    positive: позитивные сценарии
    login: тесты авторизации
    products: тесты товаров
    cart: тесты корзины
    contact: тесты формы обратной связи

log_cli = true
log_cli_level = INFO
log_cli_format = %(asctime)s [%(levelname)8s] %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S
